### ISSUE TITLE
Examples how to use this?

### ISSUE THREAD

**Issue by nardev** [onlinux/freeboard-dynamic-highcharts-plugin#1]
Would you add some examples how to use this plugin???

**Comment by onlinux** [comment]
More info about this plugin @ 
http://blog.onlinux.fr/dynamic-highcharts-plugin-for-freeboard-io/

See it in action @ https://freeboard.io/board/cnpjDa
You can clone the board and study how it works. 
Actually it is quite simple. It is a timeserie, each time you receive a data from a defined datasource, a point is plotted on the chart.

**Comment by nardev** [comment]
Please example...

**Comment by onlinux** [comment]
As I wrote in my last comment, an example is provided @ https://freeboard.io/board/cnpjDa
Clone the board at freeboard.io and enter  edit mode. You will see how it works.

**Comment by nardev** [comment]
I read your comment but i and i believe others, would appreciate a lot to have simple code/strings how the data needs to be formatted... i don't want to dig through js in that page....can't find it..

**Comment by onlinux** [comment]
Don't need to dig through js or whatever. This is a plugin for Freeboard.io. You only need to define a datasource ( as Paho MQTT, Dweet.io) at top right corner of the board. Once the datasource is defined, select the data you want to plot in edit mode.
![dynamic-highcharts-plugin-6](https://cloud.githubusercontent.com/assets/1698503/21991499/2bafc064-dc13-11e6-9bed-673dcce4e4df.png)

**Comment by nardev** [comment]
anyway

**Comment by 3nd0y** [comment]
Hi there, i'm still dont understand how to input the value. I put value which always changing in JSON format to series 1 datasource, but the chart won't show up.Only the timeseries always moving to left. And by the way  https://freeboard.io/board/cnpjDa r3Monitor is dead, it didn't refresh

**Comment by onlinux** [comment]
Hello,

If the timeserie is moving, it means that some data are processed. Please
check the floor value within the declaration of Y-AXIS.

ex: {"title":{"text" : "°F"}, "minorTickInterval":"auto", "floor":*0*}

Concerning the r3Monitor datasource, i 've defined a new random_number
datasource to feed the charts.

Regards

Eric

2017-09-19 14:36 GMT+02:00 fadli <notifications@github.com>:

**Comment by 3nd0y** [comment]
Hi Onlinux, i try to edit to "floor":*0* but it won't work. finally i found that the plugin which i used are old version, after update it, it work now! Thank you

**Comment by onlinux** [comment]
Closed
