### ISSUE TITLE
Couldn't install the plugin

### ISSUE THREAD

**Issue by maydaymiao** [onlinux/freeboard-dynamic-highcharts-plugin#3]
Hi, I have copied the plugin file into the folder and edit the index.html, but it didn't appear in the widget list. Anyone can help? Thanks.

![](https://github.com/maydaymiao/Raspberry_Pi/blob/master/image/thirdpartyplugin.PNG)
![](https://github.com/maydaymiao/Raspberry_Pi/blob/master/image/indexhtml.PNG)
![](https://github.com/maydaymiao/Raspberry_Pi/blob/master/image/widget.PNG)

**Comment by maydaymiao** [comment]
Looks like the images do not display properly, just click the broken icon, you should see my screen shot. Sorry for the inconvenience.

**Comment by onlinux** [comment]
Hello,

Try to see, with Google Chrome dev tools, if the plugins load properly.

2017-07-18 10:16 GMT+02:00 Michael Miao <notifications@github.com>:

**Comment by onlinux** [comment]
Have a look here: http://onlinux.fr/freeboard/index.html

**Comment by maydaymiao** [comment]
Hi onlinux, 
I got an error from firefox dev tool says "SyntaxError: expected expression, got '<'". Sorry I am not a JS programmer, anything I could do?

**Comment by onlinux** [comment]
I guess there is nothing to do with the plugins but with your index.html
code.

2017-07-19 7:33 GMT+02:00 Michael Miao <notifications@github.com>:

**Comment by maydaymiao** [comment]
I found I downloaded the wrong js file, am not sure why, but just use "wget ...". Anyway, now it works well, thanks for your time 👍

**Comment by onlinux** [comment]
closed
